# Generated by Django 3.2.4 on 2021-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
