# Generated by Django 3.2.4 on 2021-06-13 17:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hymnug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hymn',
            name='lyrics',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
